name: pr-checks
on:
  pull_request:
    branches: [main]
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
jobs:
  check-build:
    name: Lint and build check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup environment
        uses: ./.github/actions/setup-composite
      - run: pnpm format:check
      - run: pnpm build:changes
  verify-env-vars:
    name: Verify environment variables are on dev and prod
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup environment
        uses: ./.github/actions/setup-composite
      - run: vercel env pull .env --yes --environment=development --token=${{ secrets.VERCEL_TOKEN }}
      - run: pnpm -F api check-env-vars
      - run: vercel env pull .env --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - run: pnpm -F api check-env-vars
      - run: node packages/api/env.mjs > test.txt
      - run: ls -l test.txt
      - run: cat test.txt
