name: pr-checks
on:
  pull_request:
    branches: [main]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "pnpm"
      - run: pnpm i
  lint:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - run: pnpm format:check
  build:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - run: turbo run build --filter="...[origin/main]"
